"use client";
import {
    ChakraProvider,
    Container,
    DarkMode,
    ColorModeScript,
} from "@chakra-ui/react";
import { api } from "~/utils/api";

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                <ChakraProvider>
                    <Container>
                        <DarkMode>{children}</DarkMode>
                        <ColorModeScript initialColorMode={"dark"} />
                    </Container>
                </ChakraProvider>
            </body>
        </html>
    );
}

export default api.withTRPC(RootLayout);
