"use client";
import {
    ChakraProvider,
    Container,
    DarkMode,
    ColorModeScript,
} from "@chakra-ui/react";
import { api } from "~/utils/api";
import { createBrowserSupabaseClient } from "@supabase/auth-helpers-nextjs";

import { ReactNode, useState } from "react";
import type { AppProps } from "next/app";
import { env } from "~/env.mjs";
import { createClient } from "@supabase/supabase-js";
import { AuthContextProvider } from "~/providers/AuthContextProvider/AuthContextProvider";

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

const supabaseUrl = env.NEXT_PUBLIC_SUPABASE_PROJECT_URL;
const supabaseKey = env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

export const supabase = createClient(supabaseUrl, supabaseKey);

function RootLayout({ children }: { children: ReactNode }) {
    return (
        <html lang="en">
            <body>
                <AuthContextProvider>
                    <ChakraProvider>
                        <Container>
                            <DarkMode>{children}</DarkMode>
                            <ColorModeScript initialColorMode={"dark"} />
                        </Container>
                    </ChakraProvider>
                </AuthContextProvider>
            </body>
        </html>
    );
}

export default api.withTRPC(RootLayout);
